"""empty message

Revision ID: 0c2e298d1b31
Revises: ef5ca922f72d
Create Date: 2018-07-23 07:12:23.209896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2e298d1b31'
down_revision = 'ef5ca922f72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_daily',
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('flag_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern_daily')
    # ### end Alembic commands ###
