"""empty message

Revision ID: 0df1e8056918
Revises: 0c2e298d1b31
Create Date: 2018-08-12 22:28:48.703352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df1e8056918'
down_revision = '0c2e298d1b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_votes_daily',
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('flag_vote', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker', 'user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pattern_votes_daily')
    # ### end Alembic commands ###
