"""empty message

Revision ID: 2431a4e5e4b4
Revises: c6f8bb0ae305
Create Date: 2018-09-09 22:14:39.478204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2431a4e5e4b4'
down_revision = 'c6f8bb0ae305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_status',
    sa.Column('sync_job', sa.String(length=64), nullable=False),
    sa.Column('synced_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sync_job')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_status')
    # ### end Alembic commands ###
