"""empty message

Revision ID: 78a29ba0195d
Revises: 
Create Date: 2018-06-28 23:32:56.613537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a29ba0195d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_daily', sa.Column('close_price', sa.Integer(), nullable=True))
    op.add_column('stock_daily', sa.Column('high_price', sa.Integer(), nullable=True))
    op.add_column('stock_daily', sa.Column('low_price', sa.Integer(), nullable=True))
    op.add_column('stock_daily', sa.Column('open_price', sa.Integer(), nullable=True))
    op.add_column('stock_daily', sa.Column('volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_daily', 'volume')
    op.drop_column('stock_daily', 'open_price')
    op.drop_column('stock_daily', 'low_price')
    op.drop_column('stock_daily', 'high_price')
    op.drop_column('stock_daily', 'close_price')
    # ### end Alembic commands ###
