"""empty message

Revision ID: 879f34251d7d
Revises: 2431a4e5e4b4
Create Date: 2018-09-09 23:18:52.502733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879f34251d7d'
down_revision = '2431a4e5e4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_status', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_status', 'last_updated_at')
    # ### end Alembic commands ###
