"""empty message

Revision ID: 8ffa6d92ba0d
Revises: ed15971496bf
Create Date: 2018-08-26 23:29:31.151503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffa6d92ba0d'
down_revision = 'ed15971496bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ranking', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_ranking', 'last_updated_at')
    # ### end Alembic commands ###
