"""empty message

Revision ID: a1c2bf125ac9
Revises: 879f34251d7d
Create Date: 2018-09-11 23:20:03.008808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2bf125ac9'
down_revision = '879f34251d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_metadata', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_metadata', 'last_updated_at')
    # ### end Alembic commands ###
