"""empty message

Revision ID: b8480c0c2f30
Revises: 0df1e8056918
Create Date: 2018-08-12 23:04:51.706885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8480c0c2f30'
down_revision = '0df1e8056918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
