"""empty message

Revision ID: bf65a720f13c
Revises: 78a29ba0195d
Create Date: 2018-07-03 00:25:37.826243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf65a720f13c'
down_revision = '78a29ba0195d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_metadata',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('sector', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('stock_sync_status',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('synced_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_sync_status')
    op.drop_table('stock_metadata')
    # ### end Alembic commands ###
