"""empty message

Revision ID: c6f8bb0ae305
Revises: 8ffa6d92ba0d
Create Date: 2018-08-30 22:57:21.199947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f8bb0ae305'
down_revision = '8ffa6d92ba0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_performance',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('time_window', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'time_window')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_performance')
    # ### end Alembic commands ###
