"""empty message

Revision ID: ed15971496bf
Revises: b8480c0c2f30
Create Date: 2018-08-26 23:13:30.328111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed15971496bf'
down_revision = 'b8480c0c2f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_ranking',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('time_window', sa.String(length=5), nullable=False),
    sa.Column('ranking_type', sa.String(length=48), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'time_window', 'ranking_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_ranking')
    # ### end Alembic commands ###
