"""empty message

Revision ID: ef5ca922f72d
Revises: b3e4418689d3
Create Date: 2018-07-21 22:00:10.870039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5ca922f72d'
down_revision = 'b3e4418689d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_daily', sa.Column('close_price', sa.Float(), nullable=True))
    op.add_column('stock_daily', sa.Column('high_price', sa.Float(), nullable=True))
    op.add_column('stock_daily', sa.Column('low_price', sa.Float(), nullable=True))
    op.add_column('stock_daily', sa.Column('open_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_daily', 'open_price')
    op.drop_column('stock_daily', 'low_price')
    op.drop_column('stock_daily', 'high_price')
    op.drop_column('stock_daily', 'close_price')
    # ### end Alembic commands ###
